// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRY_RiDZMcK79FJ4gGxHqVu1m3_Xf_g1A',
    appId: '1:420863540274:web:f48390ffcaf2122d83902b',
    messagingSenderId: '420863540274',
    projectId: 'bennit-f6ace',
    authDomain: 'bennit-f6ace.firebaseapp.com',
    storageBucket: 'bennit-f6ace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEs2wP1WM2GOzYlKwMWmM2u_s2hoZs1I',
    appId: '1:420863540274:android:15596300011665a283902b',
    messagingSenderId: '420863540274',
    projectId: 'bennit-f6ace',
    storageBucket: 'bennit-f6ace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyZpJgEcZBB2-MXLsWOBWB-KTMX2h9CI',
    appId: '1:420863540274:ios:3b7f80a33e0195b983902b',
    messagingSenderId: '420863540274',
    projectId: 'bennit-f6ace',
    storageBucket: 'bennit-f6ace.appspot.com',
    iosClientId: '420863540274-7vujn0ai08scv1h7p59u8riab952rm0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bennit',
  );
}
